#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <Arduino.h>
#include "ServiceModels.h"
#include "HeartbeatPattern.h"

// -----------------------------------------------------------------------------
// General
// -----------------------------------------------------------------------------

constexpr unsigned long SERIAL_BAUD_RATE = 115200UL;
constexpr unsigned long SERIAL_WAIT_TIMEOUT_MS = 3000UL;

// -----------------------------------------------------------------------------
// Watchdog
// -----------------------------------------------------------------------------

// Hardware WDT period. The UNO R4 WDT supports at most ~5592 ms; the value
// is rounded up to the next supported period. A timer interrupt refreshes the
// WDT while the main loop is alive (see Watchdog.h).
constexpr uint32_t WATCHDOG_TIMEOUT_MS = 5000UL;

// Longest allowed gap between watchdog refreshes from the main loop. It must
// exceed the longest legitimate blocking step: a TLS connect
// (TLS_CONNECT_TIMEOUT_MS on the module) or one Wi-Fi module command that hits
// the 10 s WiFiS3 MODEM_TIMEOUT. Several timeouts in a row mean the module is
// stuck, and a reset is the intended outcome.
constexpr uint32_t LOOP_WATCHDOG_TIMEOUT_MS = 30000UL;

// After a fatal hardware fault, show the fault pattern this long, then reset
// the MCU to retry.
constexpr unsigned long HARDWARE_FAULT_RESTART_MS = 60UL * 1000UL;

// -----------------------------------------------------------------------------
// API server
// -----------------------------------------------------------------------------

constexpr uint16_t API_PORT = 80;
constexpr unsigned long API_CLIENT_TIMEOUT_MS = 1500UL;

// Request size limits protect the 32 KB of SRAM from oversized requests.
constexpr size_t API_MAX_REQUEST_LINE_LENGTH = 160;
constexpr size_t API_MAX_HEADER_LINE_LENGTH = 256;
constexpr size_t API_MAX_HEADER_COUNT = 32;

// -----------------------------------------------------------------------------
// Wi-Fi
// -----------------------------------------------------------------------------

constexpr unsigned long WIFI_RECONNECT_INTERVAL_MS = 10000UL;

// WiFi.begin() busy-waits for this long; it blocks the API and health checks.
// If association takes longer, the module keeps trying in the background and
// the next update() sees the connection.
constexpr unsigned long WIFI_CONNECT_TIMEOUT_MS = 5000UL;

// After association, wait this long for a DHCP address before reconnecting.
constexpr unsigned long WIFI_ADDRESS_TIMEOUT_MS = 20000UL;

// Raise the network alarm after the network has not been ready this long.
constexpr unsigned long WIFI_OUTAGE_ALARM_MS = 60UL * 1000UL;

// Restart the board through the watchdog after the network has not been ready
// this long, counted from boot as well. Keep it well above
// WIFI_OUTAGE_ALARM_MS, so the alarm sounds first, and long enough that an
// access point that is down does not cause rapid restart cycles.
constexpr unsigned long WIFI_OUTAGE_RESTART_MS = 5UL * 60UL * 1000UL;

// -----------------------------------------------------------------------------
// Heartbeat
// -----------------------------------------------------------------------------

// One beat of the heartbeat LED: 1000 ms is 60 beats per minute.
constexpr unsigned long HEARTBEAT_PERIOD_MS = 1000UL;

// -----------------------------------------------------------------------------
// Power
// -----------------------------------------------------------------------------

// Time the CPU sleeps after each main loop pass (see PowerManager.h). It is
// also the longest added delay before an API request is accepted and the
// timing resolution of the heartbeat LED, so keep it well below the 100 ms
// heartbeat pulses.
constexpr unsigned long IDLE_SLEEP_MS = 20UL;

// -----------------------------------------------------------------------------
// Buzzer
// -----------------------------------------------------------------------------

// Passive buzzer on a PWM pin. D9 is driven by GPT channel 7, which the core
// reserves for PWM, so the pattern and watchdog timers never take it.
constexpr uint8_t BUZZER_PIN = 9;

// Tone frequency, generated by hardware PWM at 50% duty. Most passive piezo
// buzzers are loudest near their resonance, typically 2-4 kHz.
constexpr float BUZZER_TONE_HZ = 2700.0f;

// Pattern timer rate. 100 Hz gives 10 ms resolution for the beep edges.
constexpr float BUZZER_TICK_HZ = 100.0f;

constexpr unsigned long BUZZER_TEST_DURATION_MS = 3000UL;

// Service alarm: 0-500 ms ON, 500-1000 OFF, 1000-1500 ON, 1500-6000 OFF.
constexpr unsigned long SERVICE_ALARM_PERIOD_MS = 6000UL;

// Network alarm: 0-1500 ms ON, 1500-10000 OFF.
constexpr unsigned long NETWORK_ALARM_PERIOD_MS = 10000UL;

// -----------------------------------------------------------------------------
// Health checks
// -----------------------------------------------------------------------------

// Allow the Wi-Fi coprocessor time to release the previous TLS connection.
constexpr unsigned long MINIMUM_GAP_BETWEEN_CHECKS_MS = 2000UL;

constexpr unsigned long DEFAULT_CHECK_INTERVAL_MS = 60UL * 1000UL;

// Upper bound for waiting on the HTTP response. The wait loops refresh the
// watchdog, so this may exceed LOOP_WATCHDOG_TIMEOUT_MS.
constexpr unsigned long DEFAULT_HTTP_TIMEOUT_MS = 10000UL;

// TCP connect + TLS handshake timeout passed to the Wi-Fi module. Without it,
// the module may wait longer than the R4 side (10 s) and report a stale
// result later. Older module firmware may not support it: if every check
// fails with "HTTPS connection failed", update the module firmware or set 0
// to use the module default.
constexpr int TLS_CONNECT_TIMEOUT_MS = 8000;

// A service raises the alarm after this many consecutive failed checks.
constexpr unsigned long FAILURE_THRESHOLD = 2UL;

// After a failed check, retry sooner than the normal interval so that a real
// outage reaches FAILURE_THRESHOLD quickly.
constexpr unsigned long FAILURE_RETRY_INTERVAL_MS = 15UL * 1000UL;

// Add or remove entries here.
//
// Important:
//   - host must not contain "https://"
//   - path must begin with "/"
//   - each id must be unique and URL-safe
//
// The UNO R4 WiFi certificate store must contain the root CA required by each
// HTTPS host.

const ServiceConfig SERVICE_CONFIGS[] = {
  {
    "acquiring",
    "Intraclear Old Acquiring",
    "secure.intraclear.com",
    "/api/v1/health",
    443,
    DEFAULT_CHECK_INTERVAL_MS,
    DEFAULT_HTTP_TIMEOUT_MS,
    true
  },
  {
    "website",
    "Intraclear Public Website",
    "intraclear.com",
    "/",
    443,
    DEFAULT_CHECK_INTERVAL_MS,
    DEFAULT_HTTP_TIMEOUT_MS,
    true
  },
  {
    "ebank",
    "Intraclear E-Bank",
    "ebank.intraclear.com",
    "/",
    443,
    DEFAULT_CHECK_INTERVAL_MS,
    DEFAULT_HTTP_TIMEOUT_MS,
    true
  },
  {
    "pgw",
    "Intraclear New Acquiring",
    "pgw.intraclear.com",
    "/api/v1/health",
    443,
    DEFAULT_CHECK_INTERVAL_MS,
    DEFAULT_HTTP_TIMEOUT_MS,
    false
  }
};

constexpr size_t SERVICE_COUNT =
  sizeof(SERVICE_CONFIGS) / sizeof(SERVICE_CONFIGS[0]);

static_assert(
  WIFI_CONNECT_TIMEOUT_MS + 10000UL < LOOP_WATCHDOG_TIMEOUT_MS,
  "WiFi.begin() plus one module command would outlast the loop watchdog"
);
static_assert(
  static_cast<uint32_t>(TLS_CONNECT_TIMEOUT_MS) + 10000UL < LOOP_WATCHDOG_TIMEOUT_MS,
  "A TLS connect would outlast the loop watchdog"
);
static_assert(
  WIFI_OUTAGE_RESTART_MS > WIFI_OUTAGE_ALARM_MS,
  "The outage alarm must sound before the outage restart"
);
static_assert(
  WIFI_OUTAGE_RESTART_MS >
    WIFI_CONNECT_TIMEOUT_MS + WIFI_ADDRESS_TIMEOUT_MS + WIFI_RECONNECT_INTERVAL_MS,
  "The outage restart must allow at least one full connection attempt"
);
static_assert(
  IDLE_SLEEP_MS <= 25UL,
  "Idle sleep would visibly distort the 100 ms heartbeat pulses"
);
static_assert(
  HEARTBEAT_PERIOD_MS >= HEARTBEAT_MINIMUM_PERIOD_MS,
  "The heartbeat period is too short for the pulse pattern"
);

#endif
